#!/usr/bin/env python3
"""Enrich seo-registry.ts with longer intros, more FAQs, and more howTo steps."""
import json, re, sys, os

REGISTRY = os.path.join(os.path.dirname(__file__), '..', 'src', 'lib', 'seo-registry.ts')

# ── ALL enrichment data ────────────────────────────────────────────────
ENRICH = {
  # PDF
  'compresser-pdf': {'intro': "Notre compresseur PDF en ligne vous permet de reduire la taille de vos fichiers PDF de maniere significative, jusqu'a 80% dans la plupart des cas, et ce entierement gratuitement. L'outil fonctionne directement dans votre navigateur web, sans qu'aucun fichier ne soit envoye sur un serveur distant. Votre vie privee est ainsi parfaitement respectee : vos documents confidentiels restent sur votre appareil a tout moment. Que vous ayez besoin d'envoyer un PDF par email, de le telecharger sur un site web ou de liberer de l'espace de stockage, notre solution repond a tous ces besoins. Le processus de compression utilise des algorithmes avances qui eliminent les donnees redondantes et optimisent les images integrees, tout en preservant une qualite visuelle quasi identique a l'original. Vous pouvez choisir entre plusieurs niveaux de compression selon vos besoins : compression legere pour une qualite maximale, ou compression forte pour une reduction de taille optimale. L'interface intuitive vous permet de glisser-deposer votre fichier, de selectionner le niveau souhaite et de telecharger le resultat en quelques secondes. Aucune inscription n'est requise et il n'y a aucune limite d'utilisation.", 'faq': [{'q': 'Comment compresser un PDF gratuitement ?', 'a': "Glissez-deposez votre fichier PDF dans la zone de depot ci-dessus, choisissez le niveau de compression souhaite, puis telechargez le resultat. Tout est gratuit et sans inscription."}, {'q': 'Mes fichiers sont-ils en securite ?', 'a': "Oui, a 100%. Le traitement se fait entierement dans votre navigateur web. Aucun fichier n'est envoye a nos serveurs ni stocke en ligne."}, {'q': 'Quelle est la taille maximale autorisee ?', 'a': "Comme tout est traite en local, il n'y a pas de limite stricte. La seule limitation est la memoire de votre appareil."}, {'q': 'La compression degrade-t-elle la qualite ?', 'a': "En compression legere, la perte est imperceptible. En compression forte, une legere reduction peut etre visible sur les images haute resolution."}], 'howTo': ['Glissez votre fichier PDF dans la zone de depot ou cliquez pour selectionner', 'Choisissez le niveau de compression : legere, moyenne ou forte', 'Cliquez sur Compresser et attendez le traitement', 'Telechargez votre fichier compresse']},
  'fusionner-pdf': {'intro': "Fusionnez plusieurs fichiers PDF en un seul document en quelques clics avec notre outil de fusion PDF en ligne. Que vous ayez besoin d'assembler des factures, combiner des rapports ou regrouper des documents administratifs, notre solution gratuite et sans inscription vous permet de creer un PDF unique a partir de multiples fichiers. L'interface intuitive offre une fonctionnalite de glisser-deposer pour reorganiser facilement l'ordre des fichiers avant la fusion. Tout le traitement s'effectue directement dans votre navigateur, garantissant que vos documents ne quittent jamais votre appareil. Cela signifie qu'aucune donnee n'est transferee vers un serveur externe, assurant une confidentialite totale. L'outil prend en charge la fusion de deux fichiers comme de dizaines de documents, sans aucune restriction sur le nombre ou la taille. Le resultat est un PDF proprement structure qui conserve la mise en page, les polices et les images de chaque document original. Vous pouvez ensuite telecharger le fichier fusionne instantanement.", 'faq': [{'q': 'Comment fusionner des PDF en ligne ?', 'a': "Ajoutez vos fichiers PDF dans l'outil, reorganisez-les dans l'ordre souhaite par glisser-deposer, puis cliquez sur Fusionner."}, {'q': 'Combien de fichiers puis-je fusionner ?', 'a': "Il n'y a aucune limite. Vous pouvez en combiner autant que vous le souhaitez, la contrainte etant la memoire de votre appareil."}, {'q': 'Puis-je reorganiser les pages avant de fusionner ?', 'a': "Oui, l'interface vous permet de glisser-deposer les fichiers pour changer l'ordre avant la fusion finale."}], 'howTo': ["Ajoutez vos fichiers PDF par glisser-deposer ou selection", "Reorganisez l'ordre des fichiers selon vos besoins", 'Cliquez sur Fusionner pour combiner les documents', 'Telechargez le PDF fusionne']},
  'pdf-en-images': {'intro': "Convertissez chaque page de vos documents PDF en images JPG ou PNG haute resolution avec notre convertisseur en ligne gratuit. Cet outil est ideal pour extraire des pages de PDF afin de les integrer dans des presentations, les partager sur les reseaux sociaux ou les editer dans un logiciel de retouche photo. Le traitement s'effectue entierement dans votre navigateur, sans aucun envoi de fichiers vers un serveur distant. Vous pouvez choisir entre le format JPG pour des fichiers legers ou le format PNG pour une qualite maximale avec transparence. Chaque page du PDF est convertie individuellement, vous permettant de telecharger soit toutes les pages en une archive ZIP, soit des pages specifiques selon vos besoins. La resolution de sortie est configurable, de 72 DPI pour le web a 300 DPI pour l'impression professionnelle. L'outil fonctionne avec tous les types de PDF : documents texte, formulaires, presentations et fichiers graphiques.", 'faq': [{'q': 'En quel format seront mes images ?', 'a': "Vous pouvez choisir entre JPG pour des fichiers legers adaptes au web, et PNG pour une qualite maximale avec transparence."}, {'q': 'La qualite est-elle bonne ?', 'a': "Oui, les images sont generees en haute resolution. Vous pouvez configurer la resolution de sortie jusqu'a 300 DPI pour l'impression."}, {'q': 'Puis-je convertir uniquement certaines pages ?', 'a': "Oui, l'outil vous permet de selectionner les pages specifiques a convertir plutot que l'integralite du document."}], 'howTo': ["Chargez votre fichier PDF dans l'outil", 'Choisissez le format de sortie (JPG ou PNG) et la resolution', 'Selectionnez les pages a convertir ou toutes les pages', 'Telechargez les images generees individuellement ou en ZIP']},
  'signer-pdf': {'intro': "Signez vos documents PDF directement dans votre navigateur avec notre outil de signature electronique gratuit. Plus besoin d'imprimer, signer manuellement puis scanner : dessinez votre signature a main levee ou saisissez-la au clavier, puis positionnez-la exactement la ou vous le souhaitez sur le document. L'outil est parfait pour les contrats, les bons de commande et les formulaires administratifs. Vous pouvez egalement ajouter la date de signature et du texte libre. Tout le traitement s'effectue localement dans votre navigateur, garantissant que vos documents signes ne sont jamais envoyes sur un serveur externe. L'interface vous permet de redimensionner et deplacer votre signature avec precision, de signer plusieurs endroits du meme document et d'enregistrer votre signature pour une reutilisation ulterieure. Aucune inscription n'est requise.", 'faq': [{'q': 'Ma signature est-elle juridiquement valide ?', 'a': "Notre outil cree une signature simple. Pour une valeur juridique renforcee conformement au reglement eIDAS, consultez un service certifie."}, {'q': 'Puis-je sauvegarder ma signature ?', 'a': "Oui, vous pouvez enregistrer votre signature dans le navigateur pour la reutiliser rapidement sur vos prochains documents."}, {'q': 'Comment positionner la signature ?', 'a': "Apres avoir cree votre signature, cliquez a l'endroit souhaite sur le document. Vous pouvez ensuite la redimensionner et la deplacer."}], 'howTo': ['Chargez votre document PDF', 'Dessinez votre signature a main levee ou saisissez-la au clavier', 'Positionnez et redimensionnez la signature sur le document', 'Telechargez le PDF signe']},
  'deverrouiller-pdf': {'intro': "Supprimez la protection par mot de passe de vos fichiers PDF avec notre outil de deverrouillage en ligne gratuit. Si vous possedez un document protege dont vous connaissez le mot de passe mais que vous souhaitez retirer cette contrainte, cet outil est fait pour vous. Le processus est simple : vous fournissez le mot de passe actuel et l'outil cree une copie du PDF sans protection. Le traitement s'effectue entierement dans votre navigateur, vos fichiers restent sur votre appareil. L'outil prend en charge les protections par mot de passe d'ouverture et les restrictions d'impression, de copie ou de modification. Attention : cet outil ne permet pas de contourner un mot de passe que vous ne connaissez pas, il sert uniquement a retirer la protection d'un document dont vous avez legitimement le mot de passe.", 'faq': [{'q': 'Puis-je deverrouiller un PDF dont je ne connais pas le mot de passe ?', 'a': "Non, cet outil permet uniquement de retirer la protection d'un PDF dont vous connaissez deja le mot de passe."}, {'q': 'Le fichier original est-il modifie ?', 'a': "Non, l'outil cree une nouvelle copie sans protection. Le fichier original reste intact."}, {'q': 'Quels types de protection sont retires ?', 'a': "L'outil retire la protection par mot de passe d'ouverture et les restrictions sur l'impression, la copie et la modification."}], 'howTo': ['Chargez votre fichier PDF protege', 'Saisissez le mot de passe actuel du document', 'Cliquez sur Deverrouiller pour retirer la protection', 'Telechargez le PDF sans mot de passe']},
  'proteger-pdf': {'intro': "Securisez vos documents PDF en leur ajoutant une protection par mot de passe avec notre outil gratuit en ligne. Que vous souhaitiez partager des informations confidentielles ou restreindre l'acces a vos fichiers, notre solution vous permet d'ajouter un chiffrement AES-256 a vos PDF en quelques secondes. Le processus est entierement realise dans votre navigateur, sans envoi de donnees vers un serveur. Vous pouvez choisir de proteger l'ouverture du document ou restreindre certaines actions comme l'impression, la copie ou la modification. Le chiffrement AES-256 est le meme standard utilise par les banques et les gouvernements, assurant une securite maximale pour vos documents les plus sensibles. Aucune inscription n'est requise.", 'faq': [{'q': 'Quel type de chiffrement est utilise ?', 'a': "Le chiffrement AES-256 est utilise, le meme standard que les banques et les gouvernements."}, {'q': 'Puis-je restreindre uniquement l\'impression ou la copie ?', 'a': "Oui, vous pouvez configurer des permissions detaillees : autoriser la lecture mais restreindre l'impression ou la modification."}, {'q': 'Que se passe-t-il si j\'oublie le mot de passe ?', 'a': "Il n'existe aucun moyen de recuperer un mot de passe oublie. Notez-le dans un endroit sur avant de proteger votre document."}], 'howTo': ["Chargez votre fichier PDF dans l'outil", 'Definissez un mot de passe solide', 'Choisissez les permissions : lecture seule, impression autorisee, etc.', 'Telechargez le PDF protege et chiffre']},
  # IMAGE
  'convertir-image': {'intro': "Convertissez vos images entre differents formats en un clic avec notre convertisseur d'images en ligne gratuit. L'outil prend en charge PNG, JPG, WEBP, BMP, GIF, SVG, TIFF et d'autres. Que vous ayez besoin de transformer un PNG en JPG pour reduire la taille, convertir un WEBP en PNG pour la compatibilite, ou transformer un SVG en image bitmap, notre solution repond a tous vos besoins. Le traitement est entierement realise dans votre navigateur, sans envoi de vos images vers un serveur. L'interface simple vous permet de charger une ou plusieurs images, de choisir le format de sortie et la qualite, puis de telecharger les fichiers convertis. Vous pouvez egalement ajuster la qualite de compression pour JPG et WEBP, et choisir de conserver ou non la transparence pour PNG. Aucune inscription n'est requise.", 'faq': [{'q': 'Quels formats d\'image sont pris en charge ?', 'a': "PNG, JPG, WEBP, BMP, GIF, SVG, TIFF et d'autres formats mineurs."}, {'q': 'La conversion modifie-t-elle la qualite ?', 'a': "Vers JPG ou WEBP, le niveau de qualite est reglable. Vers PNG ou BMP, la qualite originale est conservee sans perte."}, {'q': 'Puis-je convertir plusieurs images a la fois ?', 'a': "Oui, la conversion par lot est supportee. Chargez plusieurs images et convertissez-les toutes en un seul clic."}], 'howTo': ['Chargez votre image ou vos images', 'Choisissez le format de sortie souhaite', 'Ajustez la qualite si necessaire', 'Telechargez les images converties']},
  'compresser-image': {'intro': "Reduisez la taille de vos images sans perte de qualite visible grace a notre compresseur d'images en ligne gratuit. L'outil utilise des algorithmes avances qui optimisent vos fichiers JPG, PNG et WEBP en eliminant les metadonnees inutiles et en appliquant une compression intelligente. Ideal pour accelerer le chargement de votre site web, envoyer des photos par email ou economiser de l'espace de stockage. Tout le traitement s'effectue localement dans votre navigateur. Vous pouvez charger plusieurs images, choisir le niveau de compression et visualiser un apercu avant-apres pour comparer la qualite. L'outil affiche egalement le taux de compression et l'economie d'espace realisee.", 'faq': [{'q': 'Quelle reduction de taille puis-je obtenir ?', 'a': "De 30% a 80% selon le type d'image et le niveau de compression choisi."}, {'q': 'La compression est-elle avec ou sans perte ?', 'a': "Les deux modes sont disponibles : sans perte (retrait des metadonnees) et avec perte reglable pour une reduction maximale."}, {'q': 'Puis-je comparer le resultat avant de telecharger ?', 'a': "Oui, l'outil affiche un apercu avant-apres avec le taux de compression et la difference de taille."}], 'howTo': ['Chargez une ou plusieurs images', 'Choisissez le niveau de compression', 'Apercez le resultat avant-apres', 'Telechargez les images compressees']},
  'redimensionner-image': {'intro': "Redimensionnez vos images facilement avec notre outil de redimensionnement en ligne gratuit. Que vous ayez besoin de reduire la taille d'une photo pour l'envoyer par email, agrandir une image pour une impression ou ajuster les dimensions pour un site web, notre solution vous permet de modifier la largeur et la hauteur en quelques clics. Vous pouvez redimensionner en specifiant des dimensions exactes en pixels, en pourcentage, ou en utilisant des proportions predefinies adaptees aux reseaux sociaux. L'outil preserve le ratio d'aspect par defaut pour eviter toute deformation, mais vous pouvez le desactiver. Tout le traitement s'effectue dans votre navigateur sans envoi de donnees vers un serveur. L'outil prend en charge JPG, PNG, WEBP et BMP.", 'faq': [{'q': 'Comment eviter la deformation ?', 'a': "Par defaut, le ratio d'aspect est verrouille. Modifiez la largeur et la hauteur s'ajuste automatiquement."}, {'q': 'Puis-je redimensionner plusieurs images a la fois ?', 'a': "Oui, chargez plusieurs images et definissez les dimensions souhaitees. Toutes seront redimensionnees aux memes dimensions."}, {'q': 'L\'agrandissement degrade-t-il la qualite ?', 'a': "L'agrandissement peut reduire la nettete. Pour de meilleurs resultats, utilisez des images source de haute resolution."}], 'howTo': ["Chargez votre image dans l'outil", 'Entrez les nouvelles dimensions en pixels ou en pourcentage', "Activez ou desactivez le verrouillage du ratio d'aspect", 'Telechargez l\'image redimensionnee']},
  'supprimer-arriere-plan': {'intro': "Supprimez automatiquement l'arriere-plan de vos images grace a notre outil de suppression de fond en ligne gratuit. Utilisant des algorithmes d'intelligence artificielle avances, l'outil detecte le sujet principal et elimine l'arriere-plan avec precision, meme sur des images complexes avec des cheveux ou des contours irreguliers. Le resultat est une image PNG transparente utilisable pour des logos, montages photo ou visuels professionnels. Tout le traitement s'effectue dans votre navigateur, sans envoi de vos images vers un serveur. Vous pouvez affiner le resultat en ajustant le seuil de detection ou en utilisant l'outil de gomme pour les zones residuelles. L'outil prend en charge JPG, PNG et WEBP en entree et produit toujours un PNG transparent.", 'faq': [{'q': 'L\'outil fonctionne-t-il sur toutes les images ?', 'a': "Il fonctionne mieux avec un contraste eleve entre le sujet et l'arriere-plan. Les images a fond uni donnent les meilleurs resultats."}, {'q': 'Puis-je affiner le resultat manuellement ?', 'a': "Oui, apres la suppression automatique, utilisez la gomme pour les zones residuelles et l'outil de restauration pour corriger."}, {'q': 'Quel est le format du fichier de sortie ?', 'a': "Le resultat est toujours un PNG avec transparence, quel que soit le format d'entree."}], 'howTo': ["Chargez votre image dans l'outil", "L'IA detecte et supprime automatiquement l'arriere-plan", 'Ajustez le resultat avec les outils de retouche si necessaire', 'Telechargez l\'image PNG transparente']},
  'heic-vers-jpg': {'intro': "Convertissez vos photos HEIC et HEIF d'iPhone en fichiers JPG universellement compatibles avec notre convertisseur gratuit en ligne. Depuis iOS 11, Apple enregistre les photos au format HEIC par defaut, ce qui pose probleme de compatibilite. Notre outil resout ce probleme en transformant vos photos HEIC en JPG en quelques secondes, directement dans votre navigateur et sans envoi de donnees vers un serveur. Vous pouvez convertir une seule photo ou un lot entier. L'outil preserve la qualite originale tout en reduisant generalement la taille du fichier. Le format JPG obtenu est compatible avec tous les appareils et logiciels. Aucune inscription n'est requise.", 'faq': [{'q': 'Pourquoi mes photos iPhone sont-elles au format HEIC ?', 'a': "Depuis iOS 11, Apple utilise HEIC par defaut pour economiser l'espace. Ce format n'est pas universellement compatible."}, {'q': 'Puis-je convertir plusieurs fichiers a la fois ?', 'a': "Oui, la conversion par lot est supportee. Glissez-deposez plusieurs fichiers HEIC et convertissez-les tous en JPG."}, {'q': 'La conversion reduit-elle la qualite ?', 'a': "La compression JPG est avec perte, mais le niveau de qualite est reglable. Avec un reglage eleve, la difference est imperceptible."}], 'howTo': ['Chargez vos fichiers HEIC ou HEIF', 'Ajustez la qualite JPG si necessaire', 'Lancez la conversion', 'Telechargez vos photos JPG converties']},
  'generateur-favicon': {'intro': "Generez des favicons professionnels pour votre site web avec notre generateur en ligne gratuit. A partir d'une image source, l'outil cree automatiquement toutes les tailles necessaires : favicon.ico, 16x16, 32x32, 48x48, apple-touch-icon et android-chrome-192x192. Vous obtenez un package complet pret a integrer avec le code HTML pour la section head. L'outil optimise chaque taille pour une nettete maximale, meme aux plus petites resolutions. Tout le traitement s'effectue dans votre navigateur sans envoi de votre image vers un serveur. Vous pouvez previsualiser l'apparence de votre favicon dans differents contextes. L'outil prend en charge PNG, JPG, SVG et BMP en entree.", 'faq': [{'q': 'Quelle taille d\'image source dois-je utiliser ?', 'a': "Utilisez une image carree d'au moins 512x512 pixels au format PNG avec transparence pour de meilleurs resultats."}, {'q': 'Quels fichiers sont generes ?', 'a': "favicon.ico, les tailles PNG 16, 32, 48, 180 et 192 pixels, plus le code HTML d'integration."}, {'q': 'Comment integrer les favicons dans mon site ?', 'a': "Telechargez le ZIP, decompressez-le a la racine de votre site et copiez le code HTML dans la section head."}], 'howTo': ["Chargez votre image source (PNG, JPG ou SVG)", 'Previsualisez le resultat a differentes tailles', 'Generez le package complet de favicons', "Telechargez le ZIP et le code HTML d'integration"]},
  'telecharger-miniature-youtube': {'intro': "Telechargez les miniatures de n'importe quelle video YouTube en haute resolution avec notre outil gratuit en ligne. Collez l'URL d'une video YouTube et l'outil recupere instantanement toutes les tailles disponibles : 120x90, 320x180, 480x360, 640x360 et 1280x720 pixels. L'outil fonctionne entierement dans votre navigateur et ne necessite aucune inscription. Les miniatures telechargees peuvent servir pour des presentations, analyser les visuels des videos populaires ou sauvegarder une image representative d'une video. Le telechargement est rapide et fonctionne avec toutes les videos publiques ou non listees. L'interface est simple : collez l'URL, selectionnez la resolution et telechargez.", 'faq': [{'q': 'Quelles resolutions sont disponibles ?', 'a': "5 tailles : 120x90, 320x180, 480x360, 640x360 et 1280x720 pixels selon la video originale."}, {'q': 'Puis-je telecharger des miniatures de videos privees ?', 'a': "Non, l'outil fonctionne uniquement avec les videos publiques ou non listees."}, {'q': 'L\'utilisation est-elle legale ?', 'a': "Les miniatures sont des images publiques fournies par YouTube. Verifiez les conditions d'utilisation pour un usage commercial."}], 'howTo': ["Collez l'URL de la video YouTube dans le champ prevu", 'Selectionnez la resolution de miniature souhaitee', 'Cliquez sur Telecharger', "Sauvegardez l'image sur votre appareil"]},
}

# Save part 1 and continue with part 2
print(f"Part 1: {len(ENRICH)} entries defined")

# ── VIDEO ──────────────────────────────────────────────────────────────
ENRICH.update({
  'decouper-video': {'intro': "Decoupez vos videos avec precision grace a notre outil de decoupage video en ligne gratuit. Cet outil vous permet de couper les parties indesirables au debut ou a la fin d'une video, d'extraire un segment specifique ou de diviser une video en plusieurs clips. L'interface intuitive affiche une timeline visuelle avec des poignees de coupe ajustables au dixieme de seconde pres. Vous pouvez egalement saisir des timestamps exacts. Le traitement s'effectue entierement dans votre navigateur, sans envoi de vos videos vers un serveur, garantissant une confidentialite totale. L'outil prend en charge MP4, WEBM, MOV et AVI, et le fichier de sortie conserve la qualite originale sans recompression inutile.", 'faq': [{'q': 'Puis-je couper plusieurs segments ?', 'a': "Oui, vous pouvez definir plusieurs points de coupe pour extraire plusieurs segments en une seule operation."}, {'q': 'La qualite est-elle preservee apres decoupage ?', 'a': "Oui, le decoupage sans perte conserve la qualite audio et video originale lorsque le format le permet."}, {'q': 'Quels formats video sont pris en charge ?', 'a': "MP4, WEBM, MOV et AVI en entree. Le format de sortie depend du format d'entree."}], 'howTo': ['Chargez votre fichier video', 'Utilisez la timeline pour definir debut et fin', 'Ajustez les poignees de coupe avec precision', 'Telechargez le clip decoupe']},
  'compresser-video': {'intro': "Reduisez la taille de vos fichiers video sans perte de qualite visible avec notre compresseur video en ligne gratuit. Les fichiers video sont souvent volumineux et difficiles a partager. Notre outil compresse vos videos directement dans votre navigateur, sans envoi vers un serveur externe. L'algorithme optimise le debit video et audio tout en preservant une qualite satisfaisante. Vous pouvez choisir entre plusieurs niveaux de compression : leger, moyen et fort. L'outil affiche un apercu pour comparer la qualite avant et apres. Les formats MP4 et WEBM sont pris en charge, avec des options pour ajuster la resolution et le debit. Parfait pour compresser avant envoi par messagerie ou telechargement sur un site.", 'faq': [{'q': 'Quelle reduction de taille puis-je obtenir ?', 'a': "En compression moyenne, comptez 40-60% de reduction. En compression forte, jusqu'a 80%."}, {'q': 'La compression degrade-t-elle la qualite ?', 'a': "En compression legere, la perte est imperceptible. En compression forte, une legere degradation peut etre visible."}, {'q': 'Quels formats sont pris en charge ?', 'a': "MP4 et WEBM en entree et en sortie. L'audio est egalement recompressé si necessaire."}], 'howTo': ['Chargez votre fichier video', 'Choisissez le niveau de compression', 'Apercez le resultat avec l\'apercu avant-apres', 'Telechargez la video compressee']},
  'convertir-video': {'intro': "Convertissez vos fichiers video entre differents formats avec notre convertisseur en ligne gratuit. L'outil prend en charge les conversions entre MP4, WEBM, AVI, MOV et MKV, rendant n'importe quelle video compatible avec votre appareil ou logiciel. Que vous ayez besoin de convertir un MOV d'iPhone en MP4, transformer un AVI en WEBM, ou preparer un MKV pour une lecture sur TV, notre solution repond a tous vos besoins. Le traitement s'effectue entierement dans votre navigateur. Vous pouvez egalement ajuster la resolution de sortie, le debit video et le format audio.", 'faq': [{'q': 'Quels formats puis-je convertir ?', 'a': "MP4, WEBM, AVI, MOV et MKV en entree. MP4 pour la compatibilite universelle, WEBM pour le web."}, {'q': 'Puis-je changer la resolution ?', 'a': "Oui, selectionnez la resolution de sortie parmi plusieurs options ou definissez des dimensions personnalisees."}, {'q': 'La conversion prend-elle du temps ?', 'a': "Le temps depend de la taille et de votre appareil. La conversion se fait localement sans attente de serveur."}], 'howTo': ['Chargez votre fichier video', 'Choisissez le format de sortie et les parametres', 'Lancez la conversion', 'Telechargez la video convertie']},
  'ajouter-audio-video': {'intro': "Ajoutez ou remplacez la piste audio d'une video avec notre outil en ligne gratuit. Que vous souhaitiez ajouter une musique de fond, remplacer l'audio original ou superposer un commentaire vocal sur un enregistrement d'ecran, cet outil vous permet de combiner facilement une piste audio avec votre video. L'interface vous offre le choix entre remplacer l'audio existant ou melanger la nouvelle piste avec l'audio original. Vous pouvez ajuster le volume de chaque piste independamment. Tout le traitement s'effectue dans votre navigateur sans envoi de fichiers vers un serveur. L'outil prend en charge MP4, WEBM et MOV pour la video, et MP3, WAV et OGG pour l'audio.", 'faq': [{'q': 'Puis-je garder l\'audio original et ajouter une musique ?', 'a': "Oui, choisissez le mode mixage pour superposer les pistes avec un controle de volume independant."}, {'q': 'Quels formats audio sont acceptes ?', 'a': "MP3, WAV et OGG. L'audio est automatiquement converti pour correspondre au format video de sortie."}, {'q': 'La video est-elle recompressée ?', 'a': "Seule la piste audio est reencodee. La piste video est conservee sans recompression."}], 'howTo': ['Chargez votre fichier video', 'Chargez le fichier audio a ajouter', 'Choisissez le mode : remplacer ou mixer', 'Ajustez les volumes et telechargez le resultat']},
  'extraire-audio-video': {'intro': "Extrayez la piste audio d'une video et enregistrez-la au format MP3 ou WAV avec notre outil d'extraction audio en ligne gratuit. Parfait pour recuperer la musique d'un clip video, sauvegarder un podcast au format audio ou extraire un extrait sonore d'une conference. Le processus est entierement realise dans votre navigateur, sans envoi de vos fichiers vers un serveur. Vous pouvez choisir la qualite de sortie audio : MP3 pour des fichiers compacts, ou WAV pour une qualite sans perte. L'outil preserve la qualite audio originale et prend en charge MP4, WEBM, MOV, AVI et MKV.", 'faq': [{'q': 'Quel format audio dois-je choisir ?', 'a': "MP3 pour des fichiers compacts adaptes a la lecture. WAV pour une qualite sans perte pour le montage professionnel."}, {'q': 'La qualite audio est-elle preservee ?', 'a': "En WAV, la qualite originale est conservee sans perte. En MP3, vous pouvez choisir le debit."}, {'q': 'Quels formats video sont pris en charge ?', 'a': "MP4, WEBM, MOV, AVI et MKV."}], 'howTo': ['Chargez votre fichier video', 'Choisissez le format de sortie : MP3 ou WAV', 'Selectionnez la qualite audio', 'Telechargez le fichier audio extrait']},
  'video-en-gif': {'intro': "Transformez vos clips video en GIF animes avec notre convertisseur en ligne gratuit. Les GIF animes sont parfaits pour les reseaux sociaux, les messages et les demonstrations visuelles. Notre outil vous permet de convertir n'importe quel segment de video en GIF dans votre navigateur, sans envoi de fichiers vers un serveur. Vous pouvez definir le debut et la fin du segment, ajuster les dimensions, choisir le nombre d'images par seconde et optimiser la taille du fichier. L'interface vous permet de previsualiser le GIF avant de le telecharger. L'outil prend en charge MP4, WEBM et MOV.", 'faq': [{'q': 'Comment reduire la taille de mon GIF ?', 'a': "Reduisez les dimensions, diminuez les FPS ou raccourcissez la duree. L'outil affiche la taille estimee en temps reel."}, {'q': 'Puis-je ajouter du texte sur le GIF ?', 'a': "Oui, ajoutez du texte ou des captions avec des options de police, taille et couleur."}, {'q': 'Quelle est la duree maximale d\'un GIF ?', 'a': "Pas de limite stricte, mais les GIF de plus de 10 secondes deviennent volumineux. Limitez a 5-8 secondes."}], 'howTo': ['Chargez votre fichier video', 'Definissez le segment a convertir avec les poignees de coupe', 'Ajustez dimensions, FPS et qualite', 'Telechargez le GIF anime genere']},
  'supprimer-audio-video': {'intro': "Supprimez la piste audio d'une video pour obtenir un fichier video muet avec notre outil gratuit en ligne. Utile pour utiliser une video sans son pour un montage, supprimer l'audio parasite d'un enregistrement d'ecran, ou creer une video silencieuse pour les reseaux sociaux. L'outil retire la piste audio tout en conservant la piste video intacte sans recompression inutile, garantissant une qualite video parfaitement preservee. Le traitement s'effectue entierement dans votre navigateur. Vous pouvez traiter des fichiers MP4, WEBM, MOV et AVI. Le fichier de sortie est au format MP4 pour une compatibilite universelle.", 'faq': [{'q': 'La qualite video est-elle affectee ?', 'a': "Non, seule la piste audio est supprimee. La piste video est conservee sans aucune modification."}, {'q': 'Puis-je choisir le format de sortie ?', 'a': "Le format de sortie est MP4 par defaut pour une compatibilite maximale."}, {'q': 'Que se passe-t-il si la video n\'a pas d\'audio ?', 'a': "L'outil detecte les pistes audio. Si la video est deja muette, le fichier sera simplement recopie."}], 'howTo': ['Chargez votre fichier video', 'Verifiez la piste audio detectee', "Cliquez sur Supprimer l'audio", 'Telechargez la video muette en MP4']},
})

# ── DEV-SEO ────────────────────────────────────────────────────────────
ENRICH.update({
  'json-csv': {'intro': "Convertissez vos donnees JSON en CSV et inversement avec notre convertisseur en ligne gratuit. Indispensable pour les developpeurs et analystes de donnees, la conversion JSON vers CSV est parfaite pour importer des donnees d'API dans Excel ou Google Sheets, tandis que la conversion CSV vers JSON facilite l'integration de donnees tabulaires dans des applications web. L'outil detecte automatiquement la structure et gere les tableaux imbriques en aplatissant les objets JSON en colonnes CSV. Vous pouvez personnaliser le separateur, le delimiteur de texte et l'encodage. Tout le traitement s'effectue dans votre navigateur sans envoi de donnees vers un serveur, garantissant la confidentialite de vos informations. L'interface vous permet de coller directement vos donnees ou de charger un fichier, de previsualiser le resultat en temps reel et de telecharger le fichier converti.", 'faq': [{'q': 'Comment gerer les objets JSON imbriques ?', 'a': "L'outil aplatit automatiquement les objets imbriques en creant des colonnes avec des noms hierarchiques separes par des points."}, {'q': 'Puis-je choisir le separateur CSV ?', 'a': "Oui, vous pouvez selectionner virgule, point-virgule ou tabulation comme separateur."}, {'q': 'Y a-t-il une limite de taille ?', 'a': "La limite depend de la memoire de votre navigateur. Pour des fichiers de plusieurs megaoctets, le traitement peut etre plus lent."}], 'howTo': ['Collez vos donnees JSON ou chargez un fichier', 'Choisissez le sens de conversion et les options', 'Previsualisez le resultat en temps reel', 'Telechargez le fichier converti']},
  'testeur-regex': {'intro': "Testez vos expressions regulieres en temps reel avec notre testeur regex en ligne gratuit. L'outil met en surbrillance les correspondances dans votre texte a mesure que vous tapez votre regex, vous permettant de deboguer et d'affiner vos patterns instantanement. L'outil affiche visuellement chaque groupe de capture, liste toutes les correspondances et signale les erreurs de syntaxe. Vous pouvez basculer entre les flags global, insensible a la casse, multiligne et dotAll. L'outil inclut une bibliotheque de patterns predefinis pour les cas frequents : emails, URLs, numeros de telephone et adresses IP. Tout fonctionne dans votre navigateur sans envoi de donnees vers un serveur.", 'faq': [{'q': 'Quels flags regex sont supportes ?', 'a': "Les flags g, i, m, s et u sont supportes et activables individuellement."}, {'q': 'Puis-je tester des groupes de capture nommes ?', 'a': "Oui, les groupes nommes et les groupes de capture standards sont affiches individuellement avec leurs valeurs."}, {'q': 'L\'outil supporte-t-il les regex JavaScript et PCRE ?', 'a': "L'outil utilise le moteur regex JavaScript. La plupart des patterns PCRE sont compatibles."}], 'howTo': ['Saisissez votre expression reguliere dans le champ prevu', 'Tapez ou collez votre texte de test', 'Activez les flags souhaites', 'Consultez les correspondances et groupes en surbrillance']},
  'meta-tags': {'intro': "Generez les balises meta HTML optimisees pour le SEO de votre site web avec notre generateur en ligne gratuit. Les meta tags sont essentiels pour le referencement : ils indiquent aux moteurs de recherche le titre, la description et les informations de partage de vos pages. Notre outil vous permet de configurer toutes les balises necessaires : titre de page, meta description, balises Open Graph pour Facebook et LinkedIn, Twitter Cards pour X, les balises canoniques et les instructions robots. L'interface vous guide avec des indicateurs de longueur optimale et des apercus en temps reel du rendu dans les resultats de recherche Google et les partages sur les reseaux sociaux. Vous obtenez un code HTML pret a copier dans la section head de votre page.", 'faq': [{'q': 'Quelle longueur pour le titre et la description ?', 'a': "Google affiche environ 60 caracteres pour le titre et 155 pour la description. L'outil vous alerte si vous depassez."}, {'q': 'Quelles balises Open Graph dois-je inclure ?', 'a': "Les balises minimales recommandees sont og:title, og:description, og:image et og:url."}, {'q': 'Puis-je previsualiser le rendu Google ?', 'a': "Oui, l'outil affiche un apercu en temps reel du snippet Google et des cartes Twitter et Facebook."}], 'howTo': ["Renseignez le titre, la description et l'URL de votre page", "Ajoutez l'image Open Graph et les informations Twitter Card", 'Verifiez les apercus Google et reseaux sociaux', 'Copiez le code HTML genere dans votre page']},
  'sitemap-robots': {'intro': "Generez les fichiers sitemap.xml et robots.txt pour votre site web avec notre outil en ligne gratuit. Le sitemap.xml guide les moteurs de recherche vers toutes les pages importantes, tandis que le robots.txt leur indique quelles pages explorer ou ignorer. Notre generateur vous permet de creer un sitemap en entrant manuellement vos URLs ou en important un CSV, en definissant les priorites et frequences de mise a jour. Pour le robots.txt, configurez les regles d'acces pour Googlebot, Bingbot et d'autres robots d'indexation, avec des regles Allow et Disallow intuitives. Vous pouvez egalement ajouter la reference a votre sitemap dans le robots.txt.", 'faq': [{'q': 'Dois-je avoir un sitemap et un robots.txt ?', 'a': "Oui, les deux sont fortement recommandes. Le sitemap aide les moteurs a decouvrir vos pages, et le robots.txt controle les permissions."}, {'q': 'Quelle priorite attribuer a mes pages ?', 'a': "La page d'accueil generalement 1.0, les pages importantes 0.8, les pages secondaires 0.5."}, {'q': 'Comment ajouter le sitemap au robots.txt ?', 'a': "L'outil ajoute automatiquement la directive Sitemap dans le robots.txt."}], 'howTo': ['Ajoutez vos URLs pour le sitemap ou importez un CSV', 'Definissez priorites et frequences de mise a jour', 'Configurez les regles Allow/Disallow du robots.txt', 'Telechargez les deux fichiers prets a deployer']},
  'formateur-json': {'intro': "Formatez, validez et embellissez vos donnees JSON avec notre formateur en ligne gratuit. L'outil prend en charge l'indentation, la minimisation, la validation syntaxique et la conversion entre JSON compact et lisible. Que vous deboguez une reponse d'API, travailliez sur un fichier de configuration ou nettoyiez des donnees mal formatees, notre solution vous fait gagner du temps. Le formateur detecte et signale les erreurs de syntaxe avec leur position exacte. Vous pouvez choisir le niveau d'indentation, trier les cles alphabetiquement et convertir les caracteres Unicode echappes en caracteres lisibles. L'outil prend egalement en charge la conversion JSON vers YAML. Tout le traitement s'effectue dans votre navigateur sans envoi de vos donnees vers un serveur.", 'faq': [{'q': 'Comment corriger une erreur de syntaxe JSON ?', 'a': "Collez votre JSON et l'outil soulignera l'erreur avec sa position exacte. Corrigez-la et la validation se met a jour."}, {'q': 'Puis-je trier les cles alphabetiquement ?', 'a': "Oui, cochez l'option de tri alphabetique pour reorganiser les cles de vos objets JSON."}, {'q': 'L\'outil supporte-t-il JSON5 ?', 'a': "L'outil valide le JSON standard RFC 8259. Les commentaires et trailing commas sont signales comme erreurs."}], 'howTo': ['Collez ou chargez vos donnees JSON', "Choisissez le format de sortie et l'indentation", 'Corrigez les erreurs signalees', 'Copiez ou telechargez le JSON formate']},
  'url-encode-decode': {'intro': "Encodez et decodez les URLs et les parametres de requete avec notre outil en ligne gratuit. L'encodage URL est essentiel lorsque vous manipulez des parametres contenant des caracteres speciaux, des accents, des espaces ou des caracteres non ASCII. Notre outil prend en charge l'encodage et le decodage URL complet ainsi que l'encodage des composants individuels. Vous pouvez egalement encoder et decoder les donnees de formulaire au format application/x-www-form-urlencoded. L'interface vous permet de basculer instantanement entre encodage et decodage, de traiter des URLs individuelles ou des listes, et de voir les resultats en temps reel. Tout fonctionne dans votre navigateur sans envoi de donnees vers un serveur.", 'faq': [{'q': 'Quelle est la difference entre encodeURI et encodeURIComponent ?', 'a': "encodeURI preserve les caracteres de structure d'URL comme /, ?, # et &. encodeURIComponent encode tous les caracteres speciaux, adapte aux valeurs de parametres."}, {'q': 'Puis-je encoder plusieurs URLs a la fois ?', 'a': "Oui, collez une URL par ligne et encodez-les toutes en un seul clic."}, {'q': 'L\'outil gere-t-il les caracteres Unicode ?', 'a': "Oui, les caracteres Unicode sont correctement encodes en sequences percent-encoded UTF-8 conformement a la RFC 3986."}], 'howTo': ['Collez votre URL ou parametre a encoder/decoder', 'Choisissez le mode : encode ou decode', 'Selectionnez le type : URI complet ou composant', 'Copiez le resultat']},
  'css-gradient': {'intro': "Generez des codes de gradient CSS avec un apercu visuel en temps reel grace a notre generateur en ligne gratuit. L'outil vous permet de creer des gradients lineaires et radiaux complexes en ajoutant, deplacant et modifiant des points de couleur. Vous pouvez definir l'angle des gradients lineaires, la forme et la position des gradients radiaux, et ajuster les positions des arrets de couleur. L'interface affiche un apercu en temps reel et genere automatiquement le code CSS correspondant, avec les prefixes webkit et moz pour une compatibilite maximale. Vous pouvez egalement generer des gradients coniques. L'outil inclut une bibliotheque de gradients predefinis populaires comme point de depart.", 'faq': [{'q': 'Quels types de gradients sont supportes ?', 'a': "Les gradients lineaires, radiaux et coniques sont supportes avec des options de configuration specifiques."}, {'q': 'Le code genere est-il compatible avec tous les navigateurs ?', 'a': "Oui, le code inclut les prefixes -webkit- et -moz- plus la syntaxe standard."}, {'q': 'Puis-je sauvegarder mes gradients ?', 'a': "Vous pouvez copier le code CSS ou l'URL de partage qui encode votre gradient."}], 'howTo': ['Choisissez le type de gradient : lineaire, radial ou conique', 'Ajoutez et ajustez les points de couleur', "Configurez l'angle, la forme et la position", 'Copiez le code CSS genere']},
  'markdown-preview': {'intro': "Previsualisez votre Markdown en temps reel avec notre editeur en ligne gratuit. L'outil vous permet de rediger du Markdown dans un panneau et de voir instantanement le rendu HTML dans un panneau adjacent. Parfait pour rediger des fichiers README, des articles de blog ou de la documentation technique. L'editeur prend en charge la syntaxe Markdown complete plus GitHub Flavored Markdown : tableaux, listes de taches, suppression de texte et blocs de code avec coloration syntaxique. L'outil inclut une barre d'outils avec des boutons de formatage rapide. Vous pouvez exporter le resultat en HTML ou en PDF. Tout fonctionne dans votre navigateur sans envoi de donnees vers un serveur.", 'faq': [{'q': 'Quelle variante de Markdown est supportee ?', 'a': "Markdown standard plus GitHub Flavored Markdown, incluant tableaux, listes de taches et blocs de code fences."}, {'q': 'Puis-je exporter le resultat ?', 'a': "Oui, en HTML avec styles inline ou en PDF directement depuis le navigateur."}, {'q': 'La coloration syntaxique fonctionne-t-elle dans les blocs de code ?', 'a': "Oui, les blocs de code avec indication de langage beneficient d'une coloration syntaxique pour plus de 100 langages."}], 'howTo': ['Redigez votre Markdown dans le panneau de gauche', 'Consultez l\'apercu en temps reel dans le panneau de droite', "Utilisez la barre d'outils pour inserer rapidement des elements", 'Exportez en HTML ou PDF']},
  'nettoyeur-url-tracking': {'intro': "Nettoyez vos URLs en supprimant les parametres de suivi et de tracking avec notre outil en ligne gratuit. De nombreux sites ajoutent des parametres UTM et de suivi a leurs URLs pour tracer le comportement des utilisateurs : utm_source, utm_medium, utm_campaign, fbclid, gclid, ref et des dizaines d'autres. Notre outil detecte et supprime automatiquement plus de 200 parametres de suivi connus, vous permettant de partager des URLs propres qui ne compromettent pas la vie privee. Vous pouvez egalement definir des parametres personnalises a supprimer ou a conserver. L'outil traite les URLs une par une ou par lot. Tout fonctionne dans votre navigateur sans envoi de donnees vers un serveur.", 'faq': [{'q': 'Quels parametres de suivi sont supprimes ?', 'a': "Plus de 200 parametres dont utm_source, utm_medium, utm_campaign, fbclid, gclid, mc_eid, ref et bien d'autres."}, {'q': 'Puis-je conserver certains parametres ?', 'a': "Oui, vous pouvez configurer une liste blanche de parametres a conserver."}, {'q': 'L\'URL nettoyee fonctionne-t-elle toujours ?', 'a': "Oui, dans la grande majorite des cas, les parametres de suivi sont ignores par le site destination."}], 'howTo': ['Collez votre URL contenant des parametres de suivi', "L\'outil detecte et supprime automatiquement les trackers", 'Verifiez les parametres retires dans la liste', 'Copiez l\'URL nettoyee']},
})

# ── TEXT-TOOLS ─────────────────────────────────────────────────────────
ENRICH.update({
  'compteur-mots': {'intro': "Comptez les mots, les caracteres, les phrases et les paragraphes de votre texte avec notre compteur de mots en ligne gratuit. L'outil calcule egalement le temps de lecture estime base sur 250 mots par minute, ainsi que le temps de parole pour les presentations. Que vous redigiez un article, une these, un post pour les reseaux sociaux ou un discours, connaitre le nombre de mots est essentiel. Notre compteur detecte automatiquement le type de contenu et ajuste le calcul. L'interface affiche en temps reel le nombre de mots, de caracteres avec et sans espaces, de phrases et de paragraphes. Vous pouvez egalement obtenir des statistiques sur la densite des mots cles. L'outil prend en charge toutes les langues y compris les langues asiatiques.", 'faq': [{'q': 'Comment le temps de lecture est-il calcule ?', 'a': "Base sur 250 mots par minute. Vous pouvez ajuster cette valeur dans les parametres."}, {'q': 'Les caracteres asiatiques sont-ils comptes comme des mots ?', 'a': "Oui, l'outil detecte les langues asiatiques et ajuste le comptage. En japonais et chinois, chaque caractere est generalement compte comme un mot."}, {'q': 'Puis-je analyser la frequence des mots ?', 'a': "Oui, l'outil affiche les mots les plus frequents avec leur nombre d'occurrences."}], 'howTo': ['Collez ou saisissez votre texte dans la zone de saisie', 'Consultez les statistiques en temps reel dans le panneau lateral', 'Ajustez la vitesse de lecture si necessaire', "Utilisez l'analyseur de frequence pour les mots cles"]},
  'convertisseur-casse': {'intro': "Convertissez la casse de votre texte en un clic avec notre convertisseur en ligne gratuit. L'outil propose toutes les conversions courantes : MAJUSCULES, minuscules, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE et d'autres. Que vous ayez tape un texte entier en majuscules par erreur, que vous souhaitiez convertir un titre en camelCase pour du code JavaScript ou transformer des underscores en tirets pour des URLs, notre outil fait la conversion instantanement. L'interface vous permet de coller votre texte, de choisir le format de sortie parmi plus de 10 options et de copier le resultat en un clic. L'outil gere correctement les accents et les caracteres speciaux des langues europeennes. Tout fonctionne dans votre navigateur.", 'faq': [{'q': 'Quels formats de casse sont disponibles ?', 'a': "MAJUSCULES, minuscules, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE et dot.case."}, {'q': 'Le Title Case gere-t-il les articles et prepositions ?', 'a': "Oui, le Title Case intelligent ne met pas en majuscule les articles et prepositions courts sauf en debut de phrase."}, {'q': 'Puis-je convertir un texte avec des accents ?', 'a': "Oui, l'outil gere correctement les caracteres accentues de toutes les langues europeennes."}], 'howTo': ['Collez votre texte dans la zone de saisie', 'Choisissez le format de casse souhaite', 'Le resultat s\'affiche instantanement', 'Copiez le texte converti']},
  'lorem-ipsum': {'intro': "Generez du texte d'occupation Lorem Ipsum personnalise avec notre generateur en ligne gratuit. L'outil vous permet de creer du texte placeholder adapte a vos besoins : nombre de paragraphes, de phrases ou de mots, type de texte et options de formatage. Parfait pour les web designers qui ont besoin de contenu de remplacement dans leurs maquettes, les developpeurs qui testent des interfaces avec du texte realiste, ou les redacteurs qui veulent visualiser la mise en page avant d'ecrire le contenu final. Contrairement au Lorem Ipsum standard, notre generateur peut produire du texte avec des longueurs variees pour un rendu plus naturel. Vous pouvez egalement generer des listes, des titres et des blocs de citation. L'outil offre un mode copie directe dans le presse-papiers.", 'faq': [{'q': 'Puis-je generer un nombre exact de mots ?', 'a': "Oui, choisissez le mode par nombre de mots et l'outil generera exactement le nombre demande."}, {'q': 'Le texte genere est-il toujours le meme ?', 'a': "Non, chaque generation produit un texte different en melangeant les phrases du corpus Lorem Ipsum."}, {'q': 'Puis-je generer du texte thematique ?', 'a': "Oui, en plus du Lorem Ipsum classique, l'outil peut generer du texte placeholder en francais thematique."}], 'howTo': ['Choisissez le type de generation : paragraphes, phrases ou mots', 'Definissez la quantite souhaitee', 'Selectionnez les options de formatage', 'Copiez le texte genere']},
  'base64': {'intro': "Encodez et decodez des chaines en Base64 avec notre outil en ligne gratuit. L'encodage Base64 est utilise dans de nombreux contextes : integration d'images dans du CSS ou du HTML, transmission de donnees binaires dans des APIs REST, stockage de credentials d'authentification HTTP Basic, et encodage de pieces jointes dans les emails MIME. Notre outil prend en charge l'encodage et le decodage de texte UTF-8 ainsi que de donnees binaires comme les images et les fichiers. Vous pouvez encoder une image en Base64 pour l'integrer dans votre code, ou decoder une chaine Base64 pour retrouver le contenu original. L'interface simple vous permet de basculer entre encodage et decodage en un clic, de coller votre texte ou de charger un fichier, et de copier le resultat. L'outil gere correctement les caracteres Unicode et les donnees binaires.", 'faq': [{'q': 'Puis-je encoder des images en Base64 ?', 'a': "Oui, chargez une image et l'outil la convertira en chaine Base64 avec le data URI scheme approprie."}, {'q': 'L\'encodage Base64 est-il un chiffrement ?', 'a': "Non, Base64 est un encodage, pas un chiffrement. Les donnees encodees peuvent etre decodees par n'importe qui."}, {'q': 'Quelle est la limite de taille ?', 'a': "La limite depend de la memoire de votre navigateur. Pour des fichiers de plus de 50 Mo, le traitement peut etre lent."}], 'howTo': ['Collez votre texte ou chargez un fichier a encoder/decoder', 'Choisissez le mode : encode ou decode', 'Le resultat s\'affiche instantanement', 'Copiez le resultat ou telechargez le fichier decode']},
  'comparateur-texte': {'intro': "Comparez deux textes et mettez en evidence les differences avec notre comparateur en ligne gratuit. L'outil utilise un algorithme de diff intelligent qui detecte les insertions, suppressions et modifications entre deux versions d'un meme texte, puis les affiche avec un code couleur : vert pour les ajouts, rouge pour les suppressions et jaune pour les modifications. Parfait pour verifier les revisions d'un document, comparer deux versions d'un contrat ou relire des traductions. L'interface cote a cote vous permet de visualiser les deux textes avec les differences surlignees. Vous pouvez naviguer de difference en difference avec des boutons de navigation. L'outil gere les comparaisons ligne par ligne ou mot par mot, et vous permet d'ignorer les differences de casse ou d'espacement.", 'faq': [{'q': 'Quels types de differences sont detectes ?', 'a': "Insertions, suppressions et modifications, chacun affiche avec un code couleur different."}, {'q': 'Puis-je ignorer les differences d\'espacement ?', 'a': "Oui, activez l'option pour ignorer les espaces multiples et les sauts de ligne superflus."}, {'q': 'Comment naviguer entre les differences ?', 'a': "Utilisez les boutons precedent/suivant ou les raccourcis clavier pour sauter d'une difference a l'autre."}], 'howTo': ['Collez le texte original dans le panneau de gauche', 'Collez le texte modifie dans le panneau de droite', 'Consultez les differences en surbrillance', 'Naviguez entre les differences avec les boutons']},
  'separateur-nom-prenom': {'intro': "Separez les noms complets en prenom et nom de famille avec notre outil en ligne gratuit. L'outil detecte automatiquement la structure des noms et les separe intelligemment en prenom, nom de famille et eventuellement deuxieme prenom ou particule. Parfait pour nettoyer des listes de contacts, preparer des fichiers d'importation CRM ou normaliser des bases de donnees de noms. Vous pouvez traiter un nom individuel ou importer un fichier CSV avec une colonne de noms complets a separer. L'outil gere les noms composes, les particules comme de, du, van et von, les prefixes comme Dr. et Mme, et les suffixes comme Jr. et III. Le resultat peut etre exporte en CSV avec les colonnes prenom et nom separees. L'outil prend en charge les conventions francaises et internationales.", 'faq': [{'q': 'L\'outil gere-t-il les noms composes ?', 'a': "Oui, les noms composes comme Jean-Pierre ou Marie-Claire sont correctement identifies comme prenoms composes."}, {'q': 'Puis-je traiter un fichier CSV complet ?', 'a': "Oui, importez votre CSV, selectionnez la colonne contenant les noms complets, et l'outil ajoutera les colonnes prenom et nom."}, {'q': 'Les particules sont-elles gerees ?', 'a': "Oui, les particules comme de, du, van, von et el sont conservees avec le nom de famille."}], 'howTo': ['Collez un nom ou importez un fichier CSV', "L\'outil detecte automatiquement la structure du nom", 'Verifiez la separation proposee', 'Exportez le resultat en CSV ou copiez-le']},
})

print(f"Total enrichment entries: {len(ENRICH)}")

# ── Now merge into seo-registry.ts ─────────────────────────────────────
with open('src/lib/seo-registry.ts', 'r') as f:
    src = f.read()

def esc(s):
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "\\'")
    s = s.replace('\n', '\\n')
    return s

def build_faq(items):
    parts = []
    for i in items:
        q = esc(i['q'])
        a = esc(i['a'])
        parts.append(f"{{ q: '{q}', a: '{a}' }}")
    return '[\n      ' + ',\n      '.join(parts) + ',\n    ]'

def build_howto(steps):
    return '[' + ', '.join(f"'{esc(s)}'" for s in steps) + ']'

enriched = 0
for slug, data in ENRICH.items():
    pattern = f"'{slug}':\\s*\\{{"
    match = re.search(pattern, src)
    if not match:
        print(f'WARNING: slug "{slug}" not found')
        continue
    start = match.start()
    brace_count = 0
    end = start
    for i in range(start, len(src)):
        if src[i] == '{': brace_count += 1
        elif src[i] == '}':
            brace_count -= 1
            if brace_count == 0:
                end = i + 1
                break
    entry = src[start:end]
    # Replace intro
    new_intro = esc(data['intro'])
    entry = re.sub(r"intro: '(.*?)',\s*faq:", f"intro: '{new_intro}',\n    faq:", entry, flags=re.DOTALL)
    # Replace faq
    new_faq = build_faq(data['faq'])
    entry = re.sub(r'faq: \[.*?\],\s*howTo:', f'faq: {new_faq},\n    howTo:', entry, flags=re.DOTALL)
    # Replace howTo
    new_howto = build_howto(data['howTo'])
    entry = re.sub(r'howTo: \[(.*?)\]', f'howTo: {new_howto}', entry, flags=re.DOTALL)
    src = src[:start] + entry + src[end:]
    enriched += 1

with open('src/lib/seo-registry.ts', 'w') as f:
    f.write(src)

print(f'\nDone! Enriched {enriched} entries')
